### ISSUE TITLE
Can EasyCNN support google inception or resnet  network ?

### ISSUE THREAD

**Issue by minipeach** [xylcbd/EasyCNN#3]

**Comment by xylcbd** [comment]
not currently supported

**Comment by xylcbd** [comment]
the goal of this repo is building a tiny, easy, light CNN framework, which is very easy to deploy to everywhere.

**Comment by minipeach** [comment]
what a pity it is , now i am reading your source code with EasyCNN, it is excellent !  it is simple for build VGG NET which has no group and concat layer , but google‘s inception  layer is hard to define , i am looking for Solution

**Comment by xylcbd** [comment]
sounds good :-D, PR is welcomed if you got it.
