### ISSUE TITLE
Which opencv version?

### ISSUE THREAD

**Issue by LB-Yu** [xylcbd/EasyCNN#4]
Hi!

I am using VS2015 and opencv-3.4.6 to build the project. But I got an link error: *LINK : fatal error LNK1104: cannot open file“opencv_world300d.lib”*.

Could you tell me which opencv version did you use when write the project?

**Comment by xylcbd** [comment]
opencv 3.0.0

map of lib_name with version like:
opencv_world300d -> 3.0.0
opencv_world346d -> 3.4.6
...
