### ISSUE TITLE
val_loss : nan , val_accuracy : 0.0000%

### ISSUE THREAD

**Issue by xiongmingzhi** [xylcbd/EasyCNN#6]
你好，我用代码去训练我自己的数据是否是可行的，我的数据是形状是[1802,2]这样的形状，是否可行？

**Comment by xylcbd** [comment]
可以，你需要确认你的数据的标签是正确有效的，另外要确保输入形状和输出类别数符合预期：https://github.com/xylcbd/EasyCNN/blob/master/examples/mnist/mnist_train_test.cpp#L349

**Comment by xiongmingzhi** [comment]
> 可以，你需要确认你的数据是正确有效的，另外要确保输入的形状和输出类别符合标签：[https ://github.comylcbd/EasyCNN/blob/master/examples/mnist/mnist_train_test.cpp #L349](https://github.com/xylcbd/EasyCNN/blob/master/examples/mnist/mnist_train_test.cpp#L349)

非常感谢你的回复，我将我的数据放入模型中进行训练，出现epoch[19] val_loss : nan , val_accuracy : 0.0000%，这种错误，我Debug查看是因为在计算交叉熵时出现了负数，随后继续追踪数据，似乎是在前向传播中产生了负数导致的，对于这个问题我有点束手无策，希望能得到你的帮助。。。
