### ISSUE TITLE
验证集精确有96%，测试的时候标签全是错的？

### ISSUE THREAD

**Issue by xiongmingzhi** [xylcbd/EasyCNN#7]
_int main(int argc, char* argv[])
{
	EasyCNN::set_thread_num(4);

	const std::string model_file = "../res/model/mnist.modelx";
#if 0
	const std::string mnist_train_images_file = "../res/mnist_data/train-images.idx3-ubyte";
	const std::string mnist_train_labels_file = "../res/mnist_data/train-labels.idx1-ubyte";
	train(mnist_train_images_file, mnist_train_labels_file, model_file);

	//NOTE : NEVER NEVER fine tune network for the test accuracy!!!
	const std::string mnist_test_images_file = "../res/mnist_data/t10k-images.idx3-ubyte";
	const std::string mnist_test_labels_file = "../res/mnist_data/t10k-labels.idx1-ubyte";
	test(mnist_test_images_file, mnist_test_labels_file, model_file);
#else
	const std::string mnist_test_images_file = "../res/mnist_data/t10k-images.idx3-ubyte";
	const std::string mnist_test_labels_file = "../res/mnist_data/t10k-labels.idx1-ubyte";
	std::vector<std::pair<int, cv::Mat>> samples = export_random_mnist_image(mnist_test_images_file, mnist_test_labels_file, 10);
	test_single(samples, model_file);
#endif
	return 0;
}_
我在训练的时候，验证集精度能达到96%以上，训练好模型后，用test_single函数测出的结果全是错的，这是为什么？

**Comment by xylcbd** [comment]
可能模型没加载成功？

**Comment by xylcbd** [comment]
是PoolingLayer的序列化有一个bug，目前bug已修复（https://github.com/xylcbd/EasyCNN/commit/9e632c15ca13adda70ac30538cae5f47b04972ea ）。
